### PR TITLE
Add arm definitions

### PR DESCRIPTION
**Pull request by EduMenges**
These definitions are necessary when compiling for iOS because many header files depend on them.

### CODE REVIEW

**Comment by kambala-decapitator** [comment]
doesn't clang set them on its own?

**Comment by EduMenges** [comment]
> doesn't clang set them on its own?

It doesn't seem like so, at least using Ninja as generator. I've noticed that Xcode builds work fine tho. Maybe Xcode sets a different compiler or an `arm` target, idk.

**Comment by kambala-decapitator** [comment]
based on the [docs](https://cmake.org/cmake/help/latest/manual/cmake-toolchains.7.html#cross-compiling-for-ios-tvos-visionos-or-watchos) the right way is to specify `CMAKE_OSX_ARCHITECTURES`:

> The Unix Makefiles or [Ninja](https://cmake.org/cmake/help/latest/generator/Ninja.html#generator:Ninja) generators can also be used, but they require the project to handle more areas like target CPU selection and code signing.

once I add `-DCMAKE_OSX_ARCHITECTURES=arm64` to cmake configure command, project builds without errors. The command I used on a test app:

    cmake -S . -B build -G Ninja -DCMAKE_SYSTEM_NAME=iOS -DCMAKE_OSX_ARCHITECTURES=arm64

**Comment by EduMenges** [comment]
@kambala-decapitator yes, you're right, this PR doesn't make sense.

I made this correction because I was trying to compile SQLite3 for iOS and was getting an error due to the lack of `__arm__` definitions, but it turns out [this was because they are changing the `CMAKE_OSX_ARCHITECTURES` in their CMake file](https://github.com/rhuijben/sqlite-amalgamation/blob/35fe984ac1bd44a39d24aff30e867a107c37a35e/CMakeLists.txt#L408). I'm going to close this. Thanks for clarifying!

**Pull request closed without merging**
