### PR TITLE
Added platform option MAC_CATALYST_UNIVERSAL

### PR DESCRIPTION
**Pull request by oliverepper**
I need catalyst on arm64 and x86_64 for a project and added MAC_CATALYST_UNIVERSAL according to MAC_UNIVERSAL.

### CODE REVIEW

**Comment by leetal** [comment]
Do you think you could add a new pipeline test-case [here](https://github.com/leetal/ios-cmake/blob/master/.github/workflows/catalyst.yml) for the new `MAC_CATALYST_UNIVERSAL` variant?

**Review by leetal — CHANGES_REQUESTED** [review]
LGTM 👍 Just add the test and I'll merge this :)

**Comment by oliverepper** [comment]
I added the pipeline test-case.

**Review by leetal — APPROVED** [review]

**Comment by leetal** [comment]
Thanks for adding this! ⭐

**Pull request merged**
